package com.sayed.zippopotam.tests;

import com.sayed.zippopotam.enums.Country;
import com.sayed.zippopotam.model.ZipCodeResponse;
import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import io.qameta.allure.Issue;
import io.restassured.response.Response;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * How tolerant the endpoint is about the shape of the URL a client sends.
 *
 * <p>These are the mistakes real integrators make: wrong case, a trailing slash copied from the
 * documentation, an accidental double call.
 */
@Feature("URL handling")
@DisplayName("URL format tolerance")
class UrlFormatTest extends BaseApiTest {

    @DisplayName("The country code is case-insensitive")
    @ParameterizedTest(name = "[{index}] country code ''{0}''")
    @ValueSource(strings = {"us", "US", "Us", "uS"})
    @Description("Documented as lower case, but clients send whatever they have. Every casing must "
            + "return the same resource - and, critically, the same payload, not just the same status.")
    void country_code_casing_does_not_change_the_result(String countryCode) {
        Response response = zipCodeService.lookup(countryCode, "90210");

        assertThat(response.statusCode()).isEqualTo(200);

        // Deserialised rather than read with jsonPath("post code"): GPath treats the space in the
        // key as an expression separator, so the typed model is the only safe way to reach it.
        ZipCodeResponse body = response.as(ZipCodeResponse.class);
        assertThat(body.country()).isEqualTo(Country.UNITED_STATES.officialName());
        assertThat(body.postCode()).isEqualTo("90210");
    }

    @Test
    @DisplayName("Alphanumeric postal codes are case-insensitive too")
    @Description("GB outcodes are alphanumeric, so casing applies to the postal code as well.")
    void alphanumeric_postal_code_casing_does_not_change_the_result() {
        String upperCase = zipCodeService.lookup(Country.GREAT_BRITAIN, "B1").getBody().asString();
        String lowerCase = zipCodeService.lookup(Country.GREAT_BRITAIN, "b1").getBody().asString();

        assertThat(lowerCase).isEqualTo(upperCase);
    }

    @Test
    @DisplayName("The postal code is echoed back exactly as the provider stores it")
    @Description("Formatting-sensitive countries (JP, BR) use separators. The response must preserve "
            + "them, otherwise a client round-tripping the value builds a broken second request.")
    void formatted_postal_codes_are_echoed_verbatim() {
        assertThat(zipCodeService.lookupAsModel(Country.JAPAN, "100-0001").postCode()).isEqualTo("100-0001");
        assertThat(zipCodeService.lookupAsModel(Country.BRAZIL, "01000-000").postCode()).isEqualTo("01000-000");
    }

    // ------------------------------------------------------------------ known defect

    @Test
    @Tag("known-defect")
    @Issue("BUG-001")
    @DisplayName("BUG-001: the trailing-slash URL form from the documentation returns 404")
    @Description("""
            The requirements document and the zippopotam.us site both publish the endpoint as
                api.zippopotam.us/country/postal-code/
            with a trailing slash, but that exact URL returns 404 (and an HTML error page rather
            than JSON). Only the slash-less form works.

            This test asserts the DOCUMENTED behaviour, so it fails until the API and its
            documentation agree. It is excluded from the default run via the 'known-defect' tag;
            run it with: mvn test -Dexcluded.groups=none
            """)
    void documented_trailing_slash_url_should_resolve() {
        Response response = zipCodeService.lookupWithTrailingSlash(Country.UNITED_STATES.code(), "90210");

        assertThat(response.statusCode())
                .as("the URL form published in the documentation must work")
                .isEqualTo(200);
    }

    @Test
    @Tag("known-defect")
    @Issue("BUG-002")
    @DisplayName("BUG-002: some error responses are HTML instead of JSON")
    @Description("""
            /us/99999 correctly returns 404 with a JSON body, but /us (a missing path segment)
            returns a 404 HTML page generated by the web framework, which also echoes the requested
            URL back to the caller. Error handling should be uniform and machine-readable across
            every failure mode.
            """)
    void all_error_responses_should_be_json() {
        Response response = zipCodeService.getRawPath("/us");

        assertThat(response.getContentType())
                .as("error responses must be machine-readable JSON")
                .contains("application/json");
    }
}
